#!/bin/bash

# update 
echo "deb http://mirrors.ustc.edu.cn/debian stable main contrib non-free" >  /etc/apt/sources.list
echo "# deb-src http://mirrors.ustc.edu.cn/debian stable main contrib non-free" >>  /etc/apt/sources.list
echo "deb http://mirrors.ustc.edu.cn/debian stable-updates main contrib non-free" >>  /etc/apt/sources.list
apt update

#create username
username=txy_dan

#add $username
useradd -m -s /bin/bash $username

#add sudo
echo "$username ALL=(ALL) ALL" >> /etc/sudoers

#update sshd_config
echo "Port 59812" >> /etc/ssh/sshd_config
echo "ClientAliveInterval 60" >> /etc/ssh/sshd_config 
echo "ClientAliveCountMax 30" >> /etc/ssh/sshd_config

#aliyun not update this
#echo "PasswordAuthentication no" >> /etc/ssh/sshd_config

#aliyun this line is 125
sed -i '125s/yes/no/' /etc/ssh/sshd_config 

apt install ufw
systemctl enable ufw
ufw enable
ufw default allow outgoing 
ufw default deny incoming
ufw allow 59812/tcp

cp /root/.ssh/ /home/$username/.ssh -r
cd /home/$username/
chown $username:$username -R .ssh/
systemctl restart sshd

